spring.application.name=estacion-nexo
server.port=8080

# Variables para el funcionamiento de JSP y JSTL
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Esta versión no usa base de datos:
# no hay datasource, ni JPA, ni migraciones.
